test:
  adapter: sqlite3
  encoding: unicode
  database: afgtest
  pool: 2
  username: test
  password: test

development:
  adapter: sqlite3
  encoding: unicode
  database: afgdev
  pool: 2
  username: dev
  password: dev

production:
  adapter: postgresql
  encoding: unicode
  database: afg
  pool: 2
  username: prod
  password: prod
